saddle-finance/multisig-scripts

README.md
helpers.py
scripts/2022_01_15_1_sip_2_engage_admin_fee.py
scripts/2022_01_19_1_sip_3_update_pool_params.py
scripts/2022_01_28_1_sip_4_delos_multisig.py
scripts/2022_02_09_1m_sdl_to_delos.py
scripts/_template_script.py

Seems like multisig wasn't allowed to transfer sdl, so allow and transfer. Please confirm the 1M number. 
```
Tx Hash: 0xf6668e580a1a784548d840787757c1b060ac7f575215309d6262c99e2d0e0c91
Value: 0
Block: 14174271
Gas Used: 107734 / 110299 (97.7%)
│   ├── Allowed
│   │   └── target: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   └── Transfer
│       ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│       ├── to: 0x03D319a9921474B9cdE1fff1DBaFba778f9eFEb0
│       └── value: 1000000000000000000000000
│ …
```

Send 1m sdl to delos, make things more pythonic

---

helpers.py
scripts/2022_05_10_blocksec_weth_to_lps.py

https://dune.com/queries/689792
```
Tx Hash: 0x538b5e7e2c137b5558c7e5f3c221463217f3fc972e9d983aa54cec09e59f8295
Value: 0
Block: 14750757
Gas Used: 639145 / 721859 (88.5%)
├── Wrapped Ether (0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
│   ├── Approval
│   │   ├── src: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── guy: 0xD152f549545093347A162Dce210e7293f1452150
│   │   └── wad: 1356000000000000000000
│   │   ├── src: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── dst: 0xD152f549545093347A162Dce210e7293f1452150
│   │   └── wad: …
```

Send Blocksec weth to affected LPs

---

scripts/2022_05_05_1_sip_10_update_pool_params.py

Added new script to doulbe a-params of aleth, btcv2, usdv2
pools. Changes to past script is just lint.

Added script to double a-params close to SIP10 goal.

---

scripts/2022_05_26_add_frax3pool_to_minichef.py

Total SDL Reward Allocation = 2_000_000
Reward Duration = 2 month (8 weeks)
New frax3pool allocation point set to 68
LP Token deployed at: 0x0785aDDf5F7334aDB7ec40cD785EBF39bfD91520
Transaction from running mutisig script:
Tx Hash: 0x7d8202add2cf45b1906d9b809ffac0c3f818c0f23e1ea8eb219fab7c1c83fe51
Value: 0
Block: 14854984
Gas Used: 323009 / 332213 (97.2%)
```
├── MiniChefV2 (0x691ef79e40d909C715BE5e9e93738B3fF7D58534)
│   ├── LogUpdatePool
│   │   ├── pid: 1
│   │   ├── lastRewardTime: 1653666543
│   │   ├── lpSupply: 3362567772049937137407
│   │   └── …
```

Add frax3pool to mainnet minichef rewards.

---

scripts/2022_05_31_1_323m_sdl_to_BlockSec.py

BlockSec Address: 0x04B3f2Ac72AAD1Cdb12A4Cb516E2183F1D455442
Amount: 1,323,340 SDL

Send 1_323_340 SDL to BlockSec.

---

scripts/2022_06_10_frax_to_affected_lps.py

Double check math here https://docs.google.com/spreadsheets/d/1HiY-CUrpYdcr3kPFDq8Trlcjbv1zhliVJKNSjXzfF_M/edit#gid=1203837369
Has not been sent to msig yet @penandlim

send 3m frax to LPs

---

scripts/2022_07_01_add_new_alUSD_gauge_and_set_killed_on_old_gauge.py

To remedy LPsymbol issue of deployed alUSD gauge, set 'is_killed' on old alUSD Gauge and add new alUSD gauge to gauge controller

(WIP) Set 'is_killed' on old alUSD Gauge and add new alUSD gauge to controller

---

scripts/2022_07_03_set_votes_for_week_1.py

Set the weights determined by https://snapshot.org/#/saddlefinance.eth/proposal/0x81b6204967d383f035f570cea9c43dca9b51910a23fcc19638df00b4260a7a6d
```
FraxBP       0xB2Ac3382dA625eb41Fc803b57743f941a484e2a6: 7786
SLP          0xc64F8A9fe7BabecA66D3997C9d15558BF4817bE3: 1038
FraxBP-sUSD  0x104F44551386d603217450822443456229F73aE4: 447
FraxBP-alUSD 0x953693DCB2E9DDC0c1398C1b540b81b63ceA5e16: 447
Frax3pool    0x13Ba45c2B686c6db7C2E28BD3a9E8EDd24B894eD: 94
D4           0x702c1b8Ec3A77009D5898e18DA8F8959B6dF2093: 90
FraxBP-USDT  0x6EC5DD7D8E396973588f0dEFD79dCA04F844d57C: 89
WRen-sBTC    0x17Bde8EBf1E9FDA85b9Bd1a104266b394E9Db33e: 6
WCUSD        0x3dC88ee38db8C7b6DCEB447E4348e51bd87ced93: 2
USDv2        0x7B2025Bf8c5ee8Baad9da8C3E3Ee45E96ed8b8EA: 0
sUSD V3 …
```

Add gauge weight vote results for week 1

---

helpers.py
scripts/2022_07_06_update_vesting_beneficiary.py

https://etherscan.io/address/0x85f99b73d0edd9cdb3462c94ebe4c5758684bdf1

Shift beneficiary for employee vesting to multisig

---

scripts/_template_script.py
scripts/utils.py

Add nonce check logic to template script

---

helpers.py
scripts/2022_07_03_set_votes_for_week_07_07_2022__07_14_2022.py
scripts/2022_07_11_set_votes_for_week_07_14_2022__07_21_2022.py
scripts/2022_07_11_set_votes_for_week_07_14__07_21.py

Snapshot [vote](https://snapshot.org/#/saddlefinance.eth/proposal/0x0a9cbfbd2f42592a92ee59056f2b77ba1cdf49631c9fdb103eef85f700437068)
Note* USX Gauge was added before voting period and was not included this week.
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xB2Ac3382dA625eb41Fc803b57743f941a484e2a6
│   │   ├── time: 1657554921
│   │   ├── weight: 5357
│   │   └── total_weight: 9999000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xc64F8A9fe7BabecA66D3997C9d15558BF4817bE3
│   │   ├── time: 1657554921
│   │   ├── weight: 2991
│   │   └── total_weight: 9999000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: …

Change gauge weights as per snapshot vote

---

helpers.py
scripts/2022_07_11_bridge_sdl_evmos_minichef.py

```
Tx Hash: 0x3d2b640484d03c5f1b1ef1bcbb43c92b4c62cb3a960cea0e81915162a62ed81b
Value: 0
Block: 15123944
Gas Used: 228700 / 260821 (87.7%)
│   ├── Approval
│   │   ├── owner: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── spender: 0x88A69B4E698A4B090DF6CF5Bd7B2D47325Ad30A3
│   │   └── value: 187418984788359784835428
│   │   ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── to: 0x88A69B4E698A4B090DF6CF5Bd7B2D47325Ad30A3
│   │   └── value: 187418984788359784835428 …
```

Bridge SDL to Evmos's minichef

---

scripts/2022_07_08_add_USX_gauge_to_controller.py

LiquidityGaugeV5_SaddleUSXPoolLPToken deployed here: 0x50d745c2a2918A47A363A2d32becd6BBC1A53ece
**Have not posted transaction yet**
│   └── NewGauge
│       ├── addr: 0x50d745c2a2918A47A363A2d32becd6BBC1A53ece
│       ├── gauge_type: 0
│       └── weight: 0
│
└── Gnosis Safe (0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE)
└── ExecutionSuccess
├── txHash: 0x463b3c99350ca5409a634f18e7d9ab9b7a0edec68be1781505fef64757431b85
└── payment: 0

add USX pool to gauge controller

---

helpers.py
scripts/_template_script.py
scripts/utils.py

- Replaces fetching `current_nonce` from on-chain with call to gnosis API 
- formatting

Refactor fetching current nonce

---

.brownie/network-config.yaml
scripts/2022_07_29_add_FRAXUSX_gauge_to_controller.py

Gauge Address: 0x9585a54297beAa83F044866678b13d388D0180bf
Tx Hash: 0x8261813dc23f2055729ce166ac2c352de83ff88155f3f16506671cdea8ecf6a5
Value: 0
Block: 15239552
Gas Used: 121660 / 125119 (97.2%)
│   └── NewGauge
│       ├── addr: 0x9585a54297beAa83F044866678b13d388D0180bf
│       ├── gauge_type: 0
│       └── weight: 0
│
└── Gnosis Safe (0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE)
└── ExecutionSuccess
├── txHash: 0xde7d2a871c04632559df626bfbc3c2f98cae46595f9f4e621c7d4ef62ce45997
└── payment: 0

Add FRAXUSX gauge to controller, added evmos network to config

---

helpers.py
scripts/2022_07_29_SDL_to_deployer_for_optimism_minichef.py

```
Tx Hash: 0x3fdc16b072c7820b9d150961c7da9cca867240ce327a961eeb957b229f95e2f9
Value: 0
Block: 15239990
Gas Used: 65249 / 66906 (97.5%)
│   └── Transfer
│       ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│       ├── to: 0x5BDb37d0Ddea3A90F233c7B7F6b9394B6b2eef34
│       └── value: 207466980000000011927552
│   
└── Gnosis Safe (0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE)
└── ExecutionSuccess
├── txHash: 0x89094c14d8701ba5fc2b2644ceaf6d17808ec6bb8f127dced4222d6f311c02b5
└── payment: 0
```

Send SDL to deployer account for manual bridging to optimism

---

scripts/_template_script.py

Adds `multisig.preview_pending()` to template

Add `multisig.preview_pending()` to template

---

scripts/2022_08_01_53_set_votes_for_week_08_04_2022__08_11_2022.py
scripts/_template_script.py

Using the results from this proposal. https://snapshot.org/#/saddlefinance.eth/proposal/0x9b51908419a123ac6d8429380f8e925ec41d5444bb234ed0c76051f444f48b03
```
Tx Hash: 0x43cc5918657d780c0d35c35fa368c6a7f90c2981f4bff0b57a019bf80a16bbf7
Value: 0
Block: 15260750
Gas Used: 445920 / 458227 (97.3%)
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xB2Ac3382dA625eb41Fc803b57743f941a484e2a6
│   │   ├── time: 1659411712
│   │   ├── weight: 7779
│   │   └── total_weight: 10406000000000000000000
│   ├── …
```

Add a script to set votes for week of Aug 4th

---

helpers.py
scripts/2022_07_29_arb_update_minichef_rate_arbitrum.py

```
Tx Hash: 0xa4d8a7ea24c49468abffc26205662b0b12e80dea59e8bd1eb7e980136a743609
To: 0x8e6e84DDab9d13A17806d34B097102605454D147
Value: 0
Block: 18898188
Gas Used: 183909 / 187304 (98.2%)
├── Gnosis Safe (0x8e6e84DDab9d13A17806d34B097102605454D147)
│   └── SafeMultiSigTransaction
│       ├── to: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
│       ├── value: 0
│       ├── data: 0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002e4002069043d7556b1207a505eb459d18d908df29b55000000000000000000000000000000000000000000000000000000000 …
```

Update Arbitrum's minichef allocpoints

---

scripts/2022_08_08_send_5mm_SDL_to_minter.py

SDL on Minter is running low. This tx refills the minter with 5mm SDL

Sending 5mm SDL to Minter contract

---

scripts/2022_08_12_corrected_arb_update_minichef_0811_0818.py

Add corrected arb minichef update script
Tx Hash: 0x8614623623cb8f15d26840cacf4976f6cad73639cb9017626190be0f615f8428
To: 0x8e6e84DDab9d13A17806d34B097102605454D147
Value: 0
Block: 20044877
Gas Used: 181334 / 189064 (95.9%)
├── Gnosis Safe (0x8e6e84DDab9d13A17806d34B097102605454D147)
│   └── SafeMultiSigTransaction
│       ├── to: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
│       ├── value: 0
│       ├── data: 0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000668002069043d7556b1207a505eb459d18d908df29b55000000000000000000000 …

Corrected arb minichef update script 08_11 - 08_18

---

scripts/2022_08_17_56_set_votes_for_week_08_18_2022__08_25_2022.py

Snapshot vote: https://snapshot.org/#/saddlefinance.eth/proposal/0x84bd02c79de8795aab9b338fc126a29d13d54b2afaef79c66841cb81828df9c2
Tx Hash: 0xd8d48cf2ee75bfbe5bd90fca68c183c111b2b287fe12be0f535e3c4cd117dc16
Value: 0
Block: 15360147
Gas Used: 485370 / 518718 (93.6%)
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xB2Ac3382dA625eb41Fc803b57743f941a484e2a6
│   │   ├── time: 1660758654
│   │   ├── weight: 6003
│   │   └── total_weight: 8570000000000000000000
│   ├── NewGaugeWeight
│   │   ├── …

Gauge weight votes for 8_18 8_25

---

helpers.py
scripts/2022_08_15_arbitrum_signer_USDs_rewarder_update.py

Updates signer to new contract at 0x492ebE7816B6934cc55f3001E1Ac165A6c5AfaB0
Removes Kain as a signer
Adds Weston Nelson and Sam K as signers
Gnosis Safe transaction: https://gnosis-safe.io/app/arb1:0x8e6e84DDab9d13A17806d34B097102605454D147/transactions/multisig_0x8e6e84DDab9d13A17806d34B097102605454D147_0x8211539ef0f33f506785906a77c425cd457245f87af2590418fc4c9f3a6a34b7
Tx Hash: 0x14dc0f8dec4c83228a231e7c12690c9476617020478baef660410bcb9cf03685
To: 0x8e6e84DDab9d13A17806d34B097102605454D147
Value: 0
Block: 20336387
Gas Used: 151338 / 170696 (88.7%)
├── Gnosis Safe …

Arbitrum signer & USDs rewarder update

---

scripts/2022_08_29_set_votes_for_week_09_01__09_09_2022.py

- Set gauge votes for 09-01 to 09-08-2022
- Weights taken from Snapshot [results](https://snapshot.org/#/saddlefinance.eth/proposal/0x9c10d4850750b2aa1e377502fa9e6cfbc276ca7dfa5da18190d4bc7f9f7328d9)

Set gauge votes for 09-01 to 09-08-2022

---

scripts/2022_08_22_57_set_votes_for_week_08_25_2022__09_01_2022.py

https://snapshot.org/#/saddlefinance.eth/proposal/0xfe4196312099432d81ea341c19b903bfdf7a1597abb961bc081d471e57adc083

Gauge weight votes for 8-25 -- 9-01

---

scripts/2022_08_30_send_SDL_from_deployer_to_Opt_minichef.py

- Sends 500k SDL to Optimism minichef via canonical Optimism bridge

Send 500k SDL to Optimism minichef

---

abi.json
scripts/2022_08_24_opt_set_minichef_for_8-25__9-08.py

Snapshot vote here https://snapshot.org/#/saddlefinance.eth/proposal/0xfbd6d118b895bbe423a3e1ef1758694b59c48c20f0ae6c3a49ccb1e3622b4233
Output:
`❯ brownie run scripts/2022_08_24_opt_set_minichef_for_8-25__9-08.py --network optimism-main
Brownie v1.17.1 - Python development framework for Ethereum
MultisigScriptsProject is the active project.
Running 'scripts/2022_08_24_opt_set_minichef_for_8-25__9-08.py::main'...
You are using the 'optimism-main' network
Enter password for "deployer":
Transaction sent: 0x303c75304579f2e7ee47662d380d5708200a3d3006533adb4ebf48824152c99a
Gas price: 0.001 gwei   Gas limit: 47905   Nonce: 64
MinichefV2.set confirmed   Block: 20488866   Gas used: 43550 (90.91%)
Transaction sent: 0xd65688f775501ff404fa91fe1607581ee1926590a7e5875f8e8b7a92290227bd
Gas price: 0.001 …

Manual Optimism reward update for 8-25 -- 9-08

---

scripts/2022_08_22_arb_update_minichef_08_25_09_01.py

https://snapshot.org/#/saddlefinance.eth/proposal/0xfbd6d118b895bbe423a3e1ef1758694b59c48c20f0ae6c3a49ccb1e3622b4233

Reward weight vote for 8-25 9-08

---

README.md
scripts/2022_09_16_sip38_send_sdl_to_mexc.py

https://saddle-finance.slack.com/archives/C017XJU4GSJ/p1663356115846309

Txn for SIP 38 send 1.5m SDL

---

scripts/2022_09_12_1mil_SDL_from_deployer_to_Opt_minichef
scripts/2022_09_12_61_set_votes_for_week_09_15__09_22.py
scripts/2022_09_12_send_SDL_from_deployer_to_Opt_minichef.py

Setting gauge weights as per: https://snapshot.org/#/saddlefinance.eth/proposal/0x9f38ae9c474573417fd559b379c26d6a47856cbe705d07d01711804b23edf80e
Sending 2million SDL to deployer account, once executed the script will be run to bridge funds to optimism minchef. Arbitrum SDL will be bridged manually.
Current emission rate is ~ 59.3k SDL per day
Assuming current gauge weights distributed around 50% for both networks this will fund around 16-17 days of emissions
│       └── amount: 2922580542871638762049721
│
│   │   ├── from: 0x5DFbCeea7A5F6556356C7A66d2A43332755D68A5
│   │   ├── to: …

Gauge Weight Changes for 9-15-2022 9-22-2022, send 1m SDL to optimism&arbitrum minichef

---

.brownie/network-config.yaml
abis/MinichefV2.json
abis/PoolRegistry.json
abis/SwapFlashLoan.json
helpers.py
scripts/2022_09_20_kava_make_3Pool_outdated.py

- Pauses Kava 3pool
- Removes Kava 3pool from the `PoolRegistry`
- Adds Kava network to brownie config

Pausing + deprecating Kava 3Pool + adding Kava network to config

---

scripts/2022_09_20_SDL_remuneration_september_month_4.py

Sends 6.7mm SDL in remunerations to affected parties for the month of September

Send SDL remunerations for the month of September

---

scripts/2022_09_26_64_set_votes_for_week_09_29__10_06.py

https://snapshot.org/#/saddlefinance.eth/proposal/0xe72e59f14f4b58777587dbba098aa8ade99f265d4ed34c75d6b83d97bc705998

Add script for setting gauge weights 9/29 ~ 10/06

---

scripts/2022_10_10_68_set_votes_for_week_10_13__10_20.py
scripts/2022_10_10_68_set_votes_for_week_10_13__10_20_oct_remunerations.py

Gauge Weight updates from snapshot vote: https://snapshot.org/#/saddlefinance.eth/proposal/0xda1c8607e38db12bd5affe7891cb9d9e4eedb13fe7301afcb0e67d7abd10831a
Sends remunerations month 5 from sip: 
https://snapshot.org/#/saddlefinance.eth/proposal/0xf27b07ef7025aa23edb2a84d56825511ea7adff8d6164cd09a23c63c42cdc01a
Sends 500k SDL to deployer for manual bridging to arbitrum minichef
Tx Hash: 0x9e18ecb79d7dd96ac51cb692265aea2e04b80c257c2c2ef31aaae5ccab8128b6
Value: 0
Block: 15720375
Gas Used: 1044679 / 1094937 (95.4%)
├── Vesting …

Mike/gauge weights 10 13  10 20

---

helpers.py
scripts/2022_10_24_arb_update_minichef_for_week_10_27__11_04.py
scripts/2022_10_24_opt_update_minichef_for_week_10_27__11_04.py
scripts/utils.py

Snapshot: https://snapshot.org/#/saddlefinance.eth/proposal/0x1856bafbeee381c68b1872954bcaf4cbc048e5c0057894947d70b5133ab16203
Updates gnosis safe transaction service as it was recently [migrated](https://forum.gnosis-safe.io/t/transaction-service-migration-october-2022/1550)
Arbitrum Txs:
```Transaction was Mined
Tx Hash: 0x5922c27b497d675b85efea3ec1da010aba3e5e9ed8e0df96cfa9dab602031022
To: 0x8e6e84DDab9d13A17806d34B097102605454D147
Value: 0
Block: 32237320
Gas Used: 313071 / 321511 (97.4%)
├── Gnosis Safe (0x8e6e84DDab9d13A17806d34B097102605454D147)
│   └── SafeMultiSigTransaction
│       ├── to: …
```

Opt Arb Minichef Rewards 10-27 -- 11-04

---

scripts/2022_10_31_71_set_votes_for_week_11_02__11_09.py
scripts/2022_10_31_arb_13_update_minichef_for_week_11_02__11_09.py
scripts/2022_10_31_opt_update_minichef_for_week_11_02__11_09.py
scripts/utils.py

Includes 5MM SDL transfer to Minter on mainnet
Includes some changes in logic for gas savings.
* Arbitrum
* Read if weight actually needs to be changed first (save execution gas)
* Optimism
* Read if weight actually needs to be changed first (save execution gas)
* Use `MiniChef.batch(bytes data, bool revertOnFail)` to reduce the number of transactions to 1 (saves execution gas)
* utils.py
* Some changes that was not intended to be merged in was added. Removing unused function / imports.
Mainnet logs
```
Tx Hash: 0xcd04674ebe9dff4f0164046ef70d2340c5b1a42e62b54dfab880819efbef0fd5
Value: 0
Block: 15871040
Gas Used: …
```

Add scripts for setting reward rates for week 11/02 - 11/09

---

helpers.py
scripts/2022_12_16_1_5m_sdl_to_delos.py

snapshot: https://snapshot.org/#/saddlefinance.eth/proposal/0xca65737dc3c6115e80321e922dfec12f5d738f45f633d8029577b55d4498ace2

SIP 45 Refill Delos HQ

---

scripts/2022_12_24_79_send_SDL_to_minter.py
scripts/2022_12_24_arb_19_update_minichef_for_week_12_21__01_04.py
scripts/2022_12_24_opt_2_update_minichef_for_week_12_21__01_04.py

snapshot: https://snapshot.org/#/saddlefinance.eth/proposal/0xa8c13f304618793ba26d1d790e02bc800c5485634fd22a721a1d0b6dadd51baa

Minichef weights for 12-21 -- 01-04, SDL refill for minter

---

scripts/2023_01_10_kill_outdated_btc_gauges_plus_dec_remunerations.py

- Kills 
- BTCv2 gauge (0x17Bde8EBf1E9FDA85b9Bd1a104266b394E9Db33e)
- tBTCv3 gauge (0xB79B4fCF7cB4A1c4064Ff5b48F71A331880ab53a)
- Sends remunerations for December (~ 1.69m SDL)
Tx preview
```
Tx Hash: 0x22a75c2fcda0e3c7f1d200ac26a35de87dc4a6b253bab17b2aef492e8d0d46f2
Value: 0
Block: 16377163
Gas Used: 443998 / 455165 (97.5%)
│   │   ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── to: 0xa0f75491720835b36edC92D06DDc468D201e9b73
│   │   └── value: …
```

Kill outdated btc gauges and send Dec remunerations

---

helpers.py
scripts/2023_01_04_arb_20_half_minichef_emission.py
scripts/2023_01_04_opt_4_half_minichef_emission.py

Half minichef reward emissions as per SIP 47: https://snapshot.org/#/saddlefinance.eth/proposal/0x706a9e600d66fabe316696588dd689acb6ed01b193510effb6bf220b585ce716
Optimism 
```
Tx Hash: 0xc1d135f2c19b195599c815368bd9768c82e0de9fa85eaacc5b4336958adad6da
From: 0x37F24cC47573EF844496907FbA9e70C9EA060d41
To: 0x55F51A0DF2714F3CcA7acBcd9d3552A66FF5953B
Value: 0
Block: 60232955
Gas Used: 188784 / 194340 (97.1%)
├── Gnosis Safe (0x55F51A0DF2714F3CcA7acBcd9d3552A66FF5953B)
│   └── SafeMultiSigTransaction
│       ├── to: 0x998739BFdAAdde7C933B942a68053933098f9EDa
│       ├── value: 0
│       ├── data: 0x8d80ff0a0000000000000000000000000000000000000000000000000000000 …
```

added scripts to half minichef emissions

---

helpers.py
scripts/2023_01_16_arb_21_update_minichef_for_week_01_18__02_04.py
scripts/2023_01_16_opt_5_update_minichef_for_week_01_18__02_04.py

Snapshot: https://snapshot.org/#/saddlefinance.eth/proposal/0x04a8a63ba3a55a0fbc14af28b02dac88f604484fa3b473085b9af1f261bb4984
Arb:
```
MultisigScriptsProject is the active project.
Launching 'ganache-cli --accounts 10 --hardfork istanbul --fork https://rpc.ankr.com/arbitrum --gasLimit 12000000 --mnemonic brownie --port 8545 --chainId 42161'...
Running 'scripts/2023_01_16_arb_21_update_minichef_for_week_01_18__02_04.py::main'...
You are using the 'arb-main-fork' network
Transaction sent: 0xb41a6171c96a27b1c7b3b2c6b25c8ac960c67b89b65eb555061ae6ede8d7f9d5
MiniChefV2.massUpdatePools confirmed   Block: 53570411   Gas used: 170945 (1.42%)
Transaction sent: 0x61f2e0e2acda73277236e08a0b78eaf16667f6d2f26f05c78ddc8de0596fa3fd
Gas price: 0.0 gwei …
```

Minichef Reward Weight and Rate Change 01-18 -- 02-04

---

scripts/2023_01_27_fund_minichef_and_minter.py

```
Running 'scripts/2023_01_27_fund_minichef_and_minter.py::main'...
You are using the 'mainnet-fork' network
Transaction sent: 0x4cf331b966a1e1a11396d71be49a9faea3c06a70dbced21fffd9f3ea8dab9214
Vesting.release confirmed   Block: 16501857   Gas used: 56973 (0.47%)
SDL balance in multisig before transfer: 7599338068795757544444583
Transaction sent: 0x596eb1b27a0c60c1667283fd78bdf684bf55929833990e9945b6aa02fa5d6b2f
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
SDL.transfer confirmed   Block: 16501858   Gas used: 52022 (0.43%)
Transaction sent: 0x06a38d8e122b77acaea411941605bb7bf7c77ee0b0e3c672b456c427ac521fd3
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
SDL.transfer confirmed   Block: 16501859   Gas used: 37034 (0.31%)
SDL …
```

Add script for funding minichef and minter

---

scripts/2023_01_30_arb_22_set_minichef_to_0.py
scripts/2023_01_30_opt_6_set_minichef_to_0.py

snapshot: https://snapshot.org/#/saddlefinance.eth/proposal/0xfbc83d80649b7f7cd4e0c430e90b412cfdea9c85e8584245247ef05b14eeaf7b
Arbitrum: 
```
Transaction sent: 0xb41a6171c96a27b1c7b3b2c6b25c8ac960c67b89b65eb555061ae6ede8d7f9d5
MiniChefV2.massUpdatePools confirmed   Block: 56755354   Gas used: 170994 (1.42%)
Transaction sent: 0x393c4847d999902feb20233388a50d7b1c0a047fa1ef3bfb919d3ca1deee7424
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
MiniChefV2.set confirmed   Block: 56755355   Gas used: 41326 (0.34%)
Transaction sent: 0x28adff38789205d7d803dfb8690feed60388c7ca00326c2ac99606d5f7c87491
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
MiniChefV2.set confirmed   Block: 56755356   Gas used: 41326 (0.34%)
Transaction sent: …
```

Scripts to set minichef rate to 0

---

scripts/2023_02_06_remunerations_january_plus_2m_minter_refill.py

Tx logs including 
- sending out remunerations for Jan23 (~1.69m SDL)
- claiming SDL from vesting contract 
- sending 2m SDL to minter contract:
```
Tx Hash: 0x20ae30683dfa5986f6cb7b7a5b2e1ba809a577309a01fe76e113551a9bc1bde8
Value: 0
Block: 16571364
Gas Used: 482455 / 495317 (97.4%)
│   │   ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   ├── to: 0xa0f75491720835b36edC92D06DDc468D201e9b73
│   │   └── value: 388195348036185000000000
│   │   ├── from: …
```

Send remunerations for jan23, send 2m SDL to minter

---

scripts/2023_02_17_arb_set_rate_to_zero.py

Fix is tested here: https://github.com/saddle-finance/saddle-contract/pull/794

Set Rates back to zero after the fix is confirmed

---

scripts/2023_02_28_set_sperax_rewarder_0x.py

```
Transaction sent: 0xa369243dcf02f7410aadd2b34fa3853a247fae95032471e5adc1209f2a8d29a3
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
Gnosis Safe.approveHash confirmed   Block: 65525647   Gas used: 46184 (0.38%)
Transaction sent: 0xf152d5b3d28fde3f64fc8d2b12c975af430673e83b594a40a4c624bbc1a90d58
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
Gnosis Safe.approveHash confirmed   Block: 65525648   Gas used: 46184 (0.38%)
Transaction sent: 0x84331c68b72d660e7cf742e114a966d978316086281fc0f982e65bdd14024b49
Gas price: 0.0 gwei   Gas limit: 73132   Nonce: 1
Gnosis Safe.execTransaction confirmed   Block: 65525649   Gas used: 71419 (97.66%)
Tx Hash: 0x84331c68b72d660e7cf742e114a966d978316086281fc0f982e65bdd14024b49
From: …
```

Set sperax rewarder to 0x

---

scripts/2023_02_09_arb_unpause_USDs_pools.py
scripts/2023_02_09_refill_minichefs.py

- Mainnet: Refills minichefs on Arbitrum and Optimism with outstanding debt
- Arbitrum: unpauses USDs pools

Refill minichef and unpause USDs pools

---

scripts/2023_03_13_delta_one_and_minter_refill.py

```console
Running 'scripts/2023_03_13_delta_one_and_minter_refill.py::main'...
You are using the 'mainnet-fork' network
Transaction sent: 0x4cf331b966a1e1a11396d71be49a9faea3c06a70dbced21fffd9f3ea8dab9214
Vesting.release confirmed   Block: 16820550   Gas used: 56973 (0.47%)
SDL balance in multisig before transfer: 4345012.049720954
Transaction sent: 0x434b575e34b9251bd7d4429179800e9c402740870e685a2fc5bd2811a29a4882
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
SDL.transfer confirmed   Block: 16820551   Gas used: 37010 (0.31%)
Transaction sent: 0xf50071be8f8affba576854138a2a557d98f71a5d2a176ac00dc74591888c897f
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
SDL.transfer confirmed   Block: 16820552   Gas used: 51998 (0.43%) …
```

Transfer 750k to Delta One. Weekly Minter refill

---

scripts/2023_04_26_opsMsig_schedule_and_trigger_rewards.py

```
Running 'scripts/2023_04_26_opsMsig_schedule_and_trigger_rewards.py::main'...
You are using the 'arb-main-fork' network
Transaction sent: 0x94924bada1f7e34aff1e07104efd05b4345b7ea91f38b5b94a60793b45f44009
fUSDC.approve confirmed   Block: 84672704   Gas used: 48573 (0.40%)
Ops msig fUSDC balance: 9166705096
Transaction sent: 0xf9fccf0c9d862cf8ed9e2cf1dd88ec27e5ba70d976258677d0b10551d97cc9e3
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
RewardScheduler_ChildGauge_CommunityfUSDCLPToken_fUSDCV3.scheduleReward confirmed   Block: 84672705   Gas used: 209791 (1.75%)
Transaction sent: 0xc11b51d38a26928f0a26a3b459703475375622da20bc77a2266ba30eaa1fc1f1
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
SDL.transfer confirmed   Block: …
```

Add script for adding fUSDC external reward and transferring SDL to ChildGauge

---

scripts/2023_05_03_minter_refill.py
scripts/2023_05_03_opsMsig_schedule_FUSDC_reward.py

Tx Hash: 0x1141057fdc2966d7e76821e984dffb44cd9f9072cf604fc76ffbd8302281ea01
Value: 0
Block: 17184915
Gas Used: 98716 / 101357 (97.4%)
│       └── amount: 2287547564687975646879757
│
│   │   ├── from: 0x5DFbCeea7A5F6556356C7A66d2A43332755D68A5
│   │   ├── to: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   └── value: 2287547564687975646879757
│   └── Transfer
│       ├── from: …

Schedule fUSDC reward and minter refil

---

scripts/cross_chain_updates/mainnet_trigger_root_gauge_transmit_emissions.py
scripts/cross_chain_updates/sidechains_trigger_child_gauge_factory_mints.py

Remove gas limit so RPC can estimate it for us

Fix broken side chain script by removing overload params

---

scripts/2023_05_30_opsMsig_fUSDC_SDL_reward.py
scripts/2023_05_31_opsMsig_fUSDC_SDL_reward.py

- Fills fUSDC gauge with 83k SDL for the current week

Add SDL refill of fUSDC arb gauge

---

scripts/2023_05_18_minter_refill.py

Tx Hash: 0xc5c403e8524ad05247e7646442fd1e177303d5dfc12f2b0e2a10b9f56b00d91b
Value: 0
Block: 17289861
Gas Used: 98716 / 101357 (97.4%)
│       └── amount: 923354261796042617960426
│   
│   │   ├── from: 0x5DFbCeea7A5F6556356C7A66d2A43332755D68A5
│   │   ├── to: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│   │   └── value: 923354261796042617960426
│   └── Transfer
│       ├── from: …

Minter refill 5-18-23

---

README.md

Updates readme to include information about ganache v7

Update read me to use ganache v7

---

scripts/2023_05_11_minter_refill.py

Refill Minter for 1.5M SDL
```
\Transaction was Mined 
Tx Hash: 0xcea3c76c19de42499ea15fbde90823140ba8e75ad9269c193051a607992da28f
Value: 0
Block: 17238480
Gas Used: 98716 / 101357 (97.4%)
│       └── amount: 861415525114155251141552
│   
│   ├── (unknown)
│   │   ├── topic1: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
│   │   ├── topic2: 0x0000000000000000000000005dfbceea7a5f6556356c7a66d2a43332755d68a5
│   │   ├── topic3: …
```

Add minter refill script for 05/11

---

scripts/2023_06_29_minter_refill_SIP_53.py

* Claim SDL from vesting contract
* Send 10M SDL to Minter
* Execute [SIP-53](https://snapshot.org/#/saddlefinance.eth/proposal/0x8e6e3813ba636c1caa9820e6f5b7c5c94e3ccceca3d6ce43ab1b78343b8c93b8)
* [Reducing the emission will go in effect in next mining epoch
](https://github.com/saddle-finance/saddle-contract/pull/811)
```
│       └── amount: 3966235413495687468290208
│   
│   ├── (unknown)
│   │   ├── topic1: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
│   │   ├── topic2: 0x0000000000000000000000005dfbceea7a5f6556356c7a66d2a43332755d68a5
│   │   ├── topic3: …
```

feat(SIP-53): Add script to send SDL to Minter and adjust emission rate
